#!/bin/sh

# wrapper script used by the Magic Carpet 2 game engine
# Copyright 2023-2024  Petre Rodan <petre.rodan@subdimension.ro>
#
# ChangeLog
#   20241006:
#       make script compatible with both bash and FreeBSD's default 'sh' IEEE Std 1003.1 (“POSIX.1”) spec interpreter

id | grep -q 'uid=0' && {
    echo "warning: $0 should NOT be run as root. use a low privilege account instead."
}

conf="${HOME}/.config/remc2/game.cfg"
engine_conf="${HOME}/.config/remc2/config.ini"

default_config='config_attack_3.ini'

exit_err() {
    echo 'please follow the instructions by running'
    echo ''
    echo 'mcarpet2_install.sh'
    echo ''
    echo 'to properly install the game assets.'
    exit 1
}

cp_engine_conf() {
    mkdir -p "${HOME}/.config/remc2/"

    found=false
    for loc in '/usr/share/mcarpet2' '/usr/local/share/mcarpet2'; do
        [ -e "${loc}/${default_config}" ] && {
            cp -f "/${loc}/${default_config}" "${engine_conf}"
            echo ''
            echo "  default engine config copied to '${engine_conf}'"
            echo '  make sure to customize to your liking'
            echo ''
            found=true
        }
    done

    [ "${found}" = "false" ] && {
        echo 'error: cannot find game install directory, exiting'
        exit 1
    }
}

[ ! -e "${conf}" ] && {
    echo "error: ${conf} file not found, exiting"
    exit_err
}

. "${conf}"

cd "${install_dir}" || {
    echo "'${install_dir}' is an invalid install directory, exiting"
    exit_err
}

[ ! -e "${engine_conf}" ] &&
    cp_engine_conf

[ ! -e "${engine_conf}" ] && {
    echo "${engine_conf} not found, exiting"
    exit_err
}

check_assets=true

[ "${1}" = "--skip-checks" ] && check_assets=false

${check_assets} && {
    # verify the checksum of the game assets
    # otherwise if a file is slightly off the engine will simply segfault
    # making debug a nightmare
    mcarpet2_install.sh -d "${install_dir}"
    ret=$?

    [ "${ret}" != "0" ] && {
        exit_err
    }

    date > "${HOME}/.config/remc2/.last_successful_asset_check"
}

# engine config sanity checks
if [ -e "${install_dir}/biggraphics" ]; then
    grep -q '^useEnhancedGraphics = true' "${engine_conf}" || {
        echo ''
        echo ''
        echo '  since you have the HD assets, you can set'
        echo '  useEnhancedGraphics = true'
        echo "  inside ${HOME}/.config/mcarpet2/config.ini"
        echo ''
        echo ''
    }
else
    grep -q '^useEnhancedGraphics = true' "${engine_conf}" && {
        echo ''
        echo ''
        echo "  error: useEnhancedGraphics is enabled in ${engine_conf}"
        echo "  but '${install_dir}/biggraphics' is missing"
        echo '  either set'
        echo '  useEnhancedGraphics = false'
        echo '  or download the HD pack via'
        echo ''
        echo "    mcarpet2_install.sh -x -d '${install_dir}'"
        exit 1
    }
fi

if [ -L "${HOME}/.local/share/remc2" ]; then
    rm -f "${HOME}/.local/share/remc2"
    ln -s "${install_dir}" "${HOME}/.local/share/remc2"
elif [ -e "${HOME}/.local/share/remc2" ]; then
    if [ "${HOME}/.local/share/remc2" != "${install_dir}" ]; then
        echo ''
        echo "  error: '${HOME}/.local/share/remc2' exists"
        echo "  remove it before re-trying to run $0"
        exit 1
    fi
else
    ln -s "${install_dir}" "${HOME}/.local/share/remc2"
fi

"${install_dir}/remc2"

